// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddTask(arg1:string):Promise<backend.Task>;

export function GetTasks():Promise<Array<backend.Task>>;
