// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTask(arg1:string,arg2:models.Priority):Promise<models.Task>;

export function DeleteTask(arg1:number):Promise<boolean>;

export function GetTasks(arg1:boolean):Promise<Array<models.Task>>;

export function ToggleStatus(arg1:number,arg2:models.Status):Promise<models.Task>;
